CREATE TABLE IF NOT EXISTS buyer (
    buyer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    title VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS buyer_address (
    buyer_address_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city VARCHAR(100) NOT NULL,
    street VARCHAR(100) NOT NULL,
    home_number VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS orders (
    order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    buyer_id BIGINT NOT NULL,
    order_status VARCHAR(32) NOT NULL,
    order_time TIMESTAMP NOT NULL,
    payment_option VARCHAR(32) NOT NULL,
    delivery_address_id BIGINT NOT NULL,
    contact_number VARCHAR(50),
    note VARCHAR(500),
    currency VARCHAR(10) NOT NULL,
    total_price DECIMAL(19,2) NOT NULL,
    CONSTRAINT fk_orders_buyer FOREIGN KEY (buyer_id) REFERENCES buyer (buyer_id),
    CONSTRAINT fk_orders_address FOREIGN KEY (delivery_address_id) REFERENCES buyer_address (buyer_address_id)
);

CREATE TABLE IF NOT EXISTS order_item (
    order_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    item_nr INT NOT NULL,
    name VARCHAR(150) NOT NULL,
    quantity INT NOT NULL,
    price DECIMAL(19,2) NOT NULL,
    CONSTRAINT fk_order_item_order FOREIGN KEY (order_id) REFERENCES orders (order_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_orders_total_price ON orders (total_price);
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders (order_status);
CREATE INDEX IF NOT EXISTS idx_order_item_order_id ON order_item (order_id);
